dist: precise
language: python
cache: pip
sudo: false
env:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
    include:
        - node_js: "lts/*"
          language: node_js
          python: ""
          addons:
              firefox: "45.0"
          env: TEST_SUITE=js_unittests
        - node_js: "lts/*"
          language: node_js
          python: ""
          addons:
              firefox: latest-esr
          env: TEST_SUITE=js_unittests

before_install:
    - . src/ci_scripts/travis_before_install.sh

before_script:
    - . src/ci_scripts/travis_before_script.sh

script:
    - src/ci_scripts/travis.sh sqlite3 django$DJANGO_VERSION unittest

branches:
    only:
        - develop
