dist: precise
language: python
cache: pip
sudo: false
env:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
    include:
        - node_js: "lts/*"
          dist: trusty
          language: node_js
          python: ""
          addons:
              firefox: "45.0"
          env: TEST_SUITE=js_unittests
        - node_js: "lts/*"
          dist: trusty
          language: node_js
          python: ""
          addons:
              firefox: latest-esr
          env: TEST_SUITE=js_unittests
        - addons:
              firefox: "60.2.2esr"
          env:
              - TEST_SUITE=selenium
              - DJANGO_VERSION=1.11

install:
    - . src/ci_scripts/travis_install.sh

before_script:
    - . src/ci_scripts/travis_before_script.sh

script:
    - src/ci_scripts/travis.sh

after_success:
    - src/ci_scripts/travis_after_success.sh

branches:
    only:
        - develop
