site_name: WireCloud
site_description: WireCloud Documentation
repo_url: https://github.com/Wirecloud/wirecloud
theme: readthedocs
extra_css: ['https://www.fiware.org/style/fiware_readthedocs.css', 'https://www.fiware.org/style/fiware_readthedocs_processing.css']
google_analytics: ['UA-84269043-1', 'wirecloud.readthedocs.io']

pages:
- 'Introduction': 'index.md'
- 'Installation Guide': 'installation_guide.md'
- 'Administration Guide': 'administration_guide.md'
- 'User Guide': 'user_guide.md'
- 'Programmer Guide':
    - 'Application Mashup RESTful API': 'restapi/index.md'
    - 'MAC Description Language':
        - 'Introduction': 'development/macdl.md'
        - 'MACDL (XML)': 'development/macdl_xml.md'
        - 'MACDL (RDF)': 'development/macdl_rdf.md'
    - 'Widget & Operator Development':
        - 'Basic Concepts': 'development/widget_and_operators.md'
        - 'Widget API': 'widgetapi/widgetapi.md'
        - 'NGSI API': 'development/ngsi_api.md'
        - 'ObjectStorage API': 'development/object_storage_api.md'
        - 'WireCloud IDE': 'development/eclipse_ide.md'
    - 'Platform Development':
        - 'Creating themes': 'development/platform/themes.md'
        - 'Contributing': 'CONTRIBUTING.md'
        - 'Testing': 'development/platform/testing.md'
        - 'Translations': 'development/platform/translation.md'
- 'Appendix: Widgets': 'widgets.md'

plugins:
    - exclude:
        glob:
            - slides/*

markdown_extensions:
    - markdown.extensions.tables
    - pymdownx.betterem
    - pymdownx.tilde:
        subscript: False
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        provider: "github"
        user: "Wirecloud"
        repo: "wirecloud"
    - pymdownx.tasklist
    - toc:
        permalink: True
        separator: "-"
