site_name: WireCloud
theme: readthedocs
extra_css: ['css/mkdocs.css']

pages:
- 'Introduction': 'index.md'
- 'Installation Guide': 'installation_guide.md'
- 'Administration Guide': 'administration_guide.md'
- 'User Guide': 'user_guide.md'
- 'Programmer Guide':
    - 'Application Mashup RESTful API': 'restapi/index.md'
    - 'Widget & Operator Development':
        - 'Basic Concepts': 'development/widget_and_operators.md'
        - 'Widget API': 'widgetapi/widgetapi.md'
        - 'NGSI API': 'ngsi_api.md'
        - 'ObjectStorage API': 'object_storage_api.md'
        - 'WireCloud IDE': 'eclipse_ide.md'

markdown_extensions:
    - markdown_github.headerid
    - markdown_github.superfences
    - markdown_github.magiclink
    - codehilite:
        guess_lang: False
    - toc:
        permalink: True
        separator: "."
